export declare function ValidateOptions(options: {
    folderPath: any;
    timeZone: any;
    dateBasedFileNaming: undefined;
    fileName: string;
    fileNamePrefix: string;
    fileNameSuffix: string;
    fileNameExtension: string;
    dateFormat: any;
    timeFormat: any;
    logLevel: string;
    onlyFileLogging: undefined;
    slackWebhookUrl: undefined;
}): any;
export declare function SetOptions(options: {
    folderPath: any;
    timeZone: any;
    dateBasedFileNaming: undefined;
    fileName: string;
    fileNamePrefix: string;
    fileNameSuffix: string;
    fileNameExtension: string;
    dateFormat: any;
    timeFormat: any;
    logLevel: string;
    onlyFileLogging: undefined;
    slackWebhookUrl: undefined;
}): any;
export declare function GetCurrentDateFileName(): any;
export declare function GetLogFileName(): any;
