import { TDefaultOptions, TErrorType } from "./type";
export declare function SetUserOptions(option: TDefaultOptions): void;
export declare function Debug(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Trace(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Info(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Warn(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Errors(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Fatal(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Log(logLevel: any, errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Success(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
export declare function Other(errorMessage: any, serviceName: any, methodName: any, errorObj: any, errorType: TErrorType, cb: any): void;
